spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_sale
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 100MB

server:
  servlet:
    context-path: /car-sale

limit:
  per:
    page: 6