spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/car_sale_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 100MB

  flyway:
    validate-migration-naming: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/db/migration
    baseline-on-migrate: true

server:
  servlet:
    context-path: /car-sale

limit:
  per:
    page: 6
