## Postgresql Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_sale
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 100MB

## Server
server:
  servlet:
    context-path: /car-sale