CREATE TYPE region AS ENUM (
    'VINNYTSIA',
    'VOLYN',
    'DNIPRO',
    'DONETSK',
    'ZHYTOMYR',
    'ZAKARPATTIA',
    'ZAPORIZHIA',
    'IVANO_FRANKIVSK',
    'KYIV',
    'KIROVOHRAD',
    'LUGANSK',
    'LVIV',
    'MYKOLAIV',
    'ODESA',
    'POLTAVA',
    'RIVNE',
    'SUMY',
    'TERNOPIL',
    'KHARKIV',
    'KHERSON',
    'KHMELNYTSKYI',
    'CHERNIVTSI',
    'CHERNIHIV',
    'CRIMEA'
    );

CREATE TABLE IF NOT EXISTS dealerships
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    region       region,
    address      VARCHAR(255),
    phone_number varchar(255) UNIQUE,
    description  TEXT,
    CONSTRAINT PK_DEALERSHIPS PRIMARY KEY (id)
);

CREATE TYPE body_type AS ENUM (
    'SEDAN',
    'COUPE',
    'HATCHBACK',
    'STATION_WAGON',
    'SUV',
    'CROSSOVER',
    'VAN',
    'PICKUP_TRUCK',
    'CONVERTIBLE',
    'ROADSTER',
    'MINIVAN',
    'BUS',
    'TRUCK'
    );

CREATE TYPE engine_type AS ENUM (
    'PETROL',
    'DIESEL',
    'GAS',
    'HYBRID',
    'ELECTRIC'
    );

CREATE TYPE transmission AS ENUM (
    'MANUAL',
    'AUTOMATIC',
    'TIPTRONIC',
    'ROBOT',
    'VARIATOR'
    );

CREATE TYPE color AS ENUM (
    'WHITE',
    'BLACK',
    'BEIGE',
    'BLUE',
    'BROWN',
    'GREEN',
    'GREY',
    'ORANGE',
    'VIOLET',
    'RED',
    'YELLOW'
    );

CREATE TABLE IF NOT EXISTS vehicles
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vin             VARCHAR(255) UNIQUE,
    brand           VARCHAR(255),
    model           VARCHAR(255),
    body_type       body_type,
    year            BIGINT,
    engine_type     engine_type,
    engine_capacity DOUBLE PRECISION                        NOT NULL,
    horsepower      BIGINT                                  NOT NULL,
    transmission    transmission,
    mileage         BIGINT                                  NOT NULL,
    color           color,
    license_plate   VARCHAR(255) UNIQUE,
    is_used         BOOLEAN,
    dealership_id   BIGINT,
    CONSTRAINT PK_VEHICLES PRIMARY KEY (id)
);

ALTER TABLE vehicles
    ADD CONSTRAINT FK_VEHICLES_ON_DEALERSHIPS FOREIGN KEY (dealership_id) REFERENCES dealerships (id);

CREATE TYPE role AS ENUM (
    'SELLER',
    'CUSTOMER'
    );

CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname     VARCHAR(255),
    lastname      VARCHAR(255),
    email         VARCHAR(255) UNIQUE,
    password      VARCHAR(255),
    phone_number  varchar(255) UNIQUE,
    role          role,
    dealership_id BIGINT,
    CONSTRAINT PK_USERS PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_DEALERSHIPS FOREIGN KEY (dealership_id) REFERENCES dealerships (id);

CREATE TABLE IF NOT EXISTS announcements
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price       BIGINT,
    created     TIMESTAMP WITHOUT TIME ZONE,
    is_closed   BOOLEAN,
    description TEXT,
    user_id     BIGINT,
    vehicle_id  BIGINT UNIQUE,
    CONSTRAINT PK_ANNOUNCEMENTS PRIMARY KEY (id)
);

ALTER TABLE announcements
    ADD CONSTRAINT FK_ANNOUNCEMENTS_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE announcements
    ADD CONSTRAINT FK_ANNOUNCEMENTS_ON_VEHICLES FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);

CREATE TABLE IF NOT EXISTS favorites
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    announcement_id BIGINT
);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_ANNOUNCEMENTS FOREIGN KEY (announcement_id) REFERENCES announcements (id);

CREATE TABLE IF NOT EXISTS images
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255),
    type varchar(255),
    data BYTEA,
    CONSTRAINT PK_IMAGES PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dealerships_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dealership_id BIGINT,
    image_id      BIGINT UNIQUE
);

ALTER TABLE dealerships_images
    ADD CONSTRAINT FK_DEALERSHIPS_IMAGES_ON_DEALERSHIPS FOREIGN KEY (dealership_id) REFERENCES dealerships (id);

ALTER TABLE dealerships_images
    ADD CONSTRAINT FK_DEALERSHIPS_IMAGES_ON_IMAGES FOREIGN KEY (image_id) REFERENCES images (id);

CREATE TABLE IF NOT EXISTS announcements_images
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    announcement_id BIGINT,
    image_id        BIGINT UNIQUE
);

ALTER TABLE announcements_images
    ADD CONSTRAINT FK_ANNOUNCEMENTS_IMAGES_ON_ANNOUNCEMENTS FOREIGN KEY (announcement_id) REFERENCES announcements (id);

ALTER TABLE announcements_images
    ADD CONSTRAINT FK_ANNOUNCEMENTS_IMAGES_ON_IMAGES FOREIGN KEY (image_id) REFERENCES images (id);

CREATE TABLE IF NOT EXISTS users_images
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT UNIQUE,
    image_id BIGINT UNIQUE
);

ALTER TABLE users_images
    ADD CONSTRAINT FK_USERS_IMAGES_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_images
    ADD CONSTRAINT FK_USERS_IMAGES_ON_IMAGES FOREIGN KEY (image_id) REFERENCES images (id);